[package]
name = "rusty_backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name="myapp"
path="src/main.rs"

[dependencies]
actix-web = "4.11.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
